### ISSUE TITLE
ZiiPOS - Windows Printers RPC Error

### ISSUE THREAD

**Issue by infinitysky** [infinitysky/ZiiPOS-Bug-tracking#4]

**Comment by infinitysky** [comment]
![image](https://user-images.githubusercontent.com/1997572/133984475-314dfd7e-d8d3-4cc2-9169-d0e80d947134.png)

**Comment by infinitysky** [comment]
![image](https://user-images.githubusercontent.com/1997572/133998005-76b23f55-2032-4e89-81a5-8a256f8c682b.png)

**Comment by infinitysky** [comment]
The Print Spooler service terminated unexpectedly.  It has done this 3 time(s).

```
The Print Spooler service terminated unexpectedly.  It has done this 1 time(s).  The following corrective action will be taken in 5000 milliseconds: Restart the service.

```


```
Faulting application name: spoolsv.exe, version: 10.0.19041.1237, time stamp: 0x8dc06a84
Faulting module name: ntdll.dll, version: 10.0.19041.1202, time stamp: 0x4f115fac
Exception code: 0xc0000374
Fault offset: 0x00000000000ff199
Faulting process id: 0xd4c
Faulting application start time: 0x01d7aa2a69a138ac
Faulting application path: C:\Windows\System32\spoolsv.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 2c89cb5e-69f9-4c61-bd6c-a34ddaba4cba
Faulting package full name: 
Faulting package-relative application ID: 

```

```
The Collect procedure for service "Spooler" in DLL "C:\Windows\System32\winspool.drv" failed with error code The RPC server is unavailable.. The performance data returned by the counter DLL will not be returned in the Perf Data Block.

```

**Comment by infinitysky** [comment]
>>[LOG TIME]：2021-09-20 19:50:19,152 [THREAD ID]：5 
[LOG LEVEL]：ERROR 
[LOG TAGERT]：logerror 
[CONTENT]：b:tas-office
file:PrinterQueueManager.cs
line:118
method:PrintServerProcess
msg:Invalid object name 'printjob'.
ex:Invalid object name 'printjob'.
  System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'printjob'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1064
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1083
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 725
   at Zii.Quokka.Data.Repository.PrintJobQueueRepository.ListActiveAsyncPrintJobs(DateTime updateStartTime, DateTime updateEndTime) in C:\Users\Maon\Source\Repos\desktop.quokka.core\Zii.Quokka.Data.Repository\PrintJobQueueRepository.cs:line 26
   at Zii.Quokka.Data.Service.Application.Impl.PrintJobQueueService.ListActiveAsyncPrintJobs(DateTime updateStartTime, DateTime updateEndTime) in C:\Users\Maon\Source\Repos\desktop.quokka.core\Zii.Quokka.Data.Service\Application\Impl\PrintJobQueueService.cs:line 19
   at Zii.Quokka.Facade.Print.PrinterQueueManager.ListActiveAsyncPrintJobs() in C:\Users\Maon\Source\Repos\desktop.quokka.core\Zii.Quokka.Facade\Print\PrinterQueueManager.cs:line 68
   at Zii.Quokka.Facade.Print.PrinterQueueManager.PrintServerProcess() in C:\Users\Maon\Source\Repos\desktop.quokka.core\Zii.Quokka.Facade\Print\PrinterQueueManager.cs:line 101
ClientConnectionId:617971b7-fa33-4e62-8a35-d46d8a95def6
Error Number:208,State:1,Class:16

**Comment by infinitysky** [comment]
Caused by Spooling
